### ISSUE TITLE
About Open Source

### ISSUE THREAD

**Issue by yxltya** [zhang-tao-whu/PCM#1]
Hello, may I ask when the code for this job can be open source?

**Comment by zhang-tao-whu** [comment]
Thanks for your attention. The code will be released in 1-2 weeks.

**Comment by Longlongint5** [comment]
Hi, is this code about to be open source soon?I am very interested in your work and thank you for your contributions.

**Comment by zhang-tao-whu** [comment]
Thanks for your attention. The codes and weights are now available at [here](https://github.com/SkyworkAI/PointCloudMamba).
